<a href="https://colab.research.google.com/github/alphadev3296/deep-learning-practice-03/blob/main/Deep_Learning_Practice-03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
"""Linear Regression"""

import torch
from torch import nn
from torch.nn import functional as F
from torch import optim

torch.manual_seed(1)

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs+1):
  hyperthesis = x_train * W + b
  cost = torch.mean((hyperthesis - y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print(f"Epoch {epoch:4d}/{nb_epochs} W:{W.item():.3f}, b:{b.item():.3f} Cost: {cost.item():.6f}")

Epoch    0/2000 W:0.187, b:0.080 Cost: 18.666666
Epoch  100/2000 W:1.746, b:0.578 Cost: 0.048171
Epoch  200/2000 W:1.800, b:0.454 Cost: 0.029767
Epoch  300/2000 W:1.843, b:0.357 Cost: 0.018394
Epoch  400/2000 W:1.876, b:0.281 Cost: 0.011366
Epoch  500/2000 W:1.903, b:0.221 Cost: 0.007024
Epoch  600/2000 W:1.924, b:0.174 Cost: 0.004340
Epoch  700/2000 W:1.940, b:0.136 Cost: 0.002682
Epoch  800/2000 W:1.953, b:0.107 Cost: 0.001657
Epoch  900/2000 W:1.963, b:0.084 Cost: 0.001024
Epoch 1000/2000 W:1.971, b:0.066 Cost: 0.000633
Epoch 1100/2000 W:1.977, b:0.052 Cost: 0.000391
Epoch 1200/2000 W:1.982, b:0.041 Cost: 0.000242
Epoch 1300/2000 W:1.986, b:0.032 Cost: 0.000149
Epoch 1400/2000 W:1.989, b:0.025 Cost: 0.000092
Epoch 1500/2000 W:1.991, b:0.020 Cost: 0.000057
Epoch 1600/2000 W:1.993, b:0.016 Cost: 0.000035
Epoch 1700/2000 W:1.995, b:0.012 Cost: 0.000022
Epoch 1800/2000 W:1.996, b:0.010 Cost: 0.000013
Epoch 1900/2000 W:1.997, b:0.008 Cost: 0.000008
Epoch 2000/2000 W:1.997, b:0.006 Cost: 

In [70]:
"""Multivariable Linear Regression - 1"""

import torch
from torch import nn
from torch.nn import functional as F
from torch import optim

torch.manual_seed(1)

x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 10000
for epoch in range(nb_epochs+1):
  hyperthesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

  cost = torch.mean((hyperthesis - y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 1000 == 0:
    print(f"Epoch {epoch:4d}/{nb_epochs} w1: {w1.item():.3f} w2: {w2.item():.3f} w3: {w3.item():.3f} b: {b.item():.3f} Cost: {cost.item():.6f}")

Epoch    0/10000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch 1000/10000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390
Epoch 2000/10000 w1: 0.757 w2: 0.571 w3: 0.682 b: 0.011 Cost: 0.754379
Epoch 3000/10000 w1: 0.788 w2: 0.541 w3: 0.682 b: 0.012 Cost: 0.562653
Epoch 4000/10000 w1: 0.812 w2: 0.517 w3: 0.681 b: 0.013 Cost: 0.448557
Epoch 5000/10000 w1: 0.832 w2: 0.500 w3: 0.678 b: 0.014 Cost: 0.379739
Epoch 6000/10000 w1: 0.848 w2: 0.488 w3: 0.675 b: 0.015 Cost: 0.337360
Epoch 7000/10000 w1: 0.861 w2: 0.478 w3: 0.671 b: 0.016 Cost: 0.310474
Epoch 8000/10000 w1: 0.871 w2: 0.472 w3: 0.667 b: 0.018 Cost: 0.292709
Epoch 9000/10000 w1: 0.880 w2: 0.467 w3: 0.663 b: 0.019 Cost: 0.280348
Epoch 10000/10000 w1: 0.888 w2: 0.464 w3: 0.658 b: 0.020 Cost: 0.271223


In [76]:
"""Multivariable Linear Regresion - 2"""

import torch
from torch import nn
from torch.nn import functional as F
from torch import optim

torch.manual_seed(1)

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

w = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w, b], lr=1e-5)

nb_epochs = 10000
for epoch in range(nb_epochs+1):
  hyperthesis = x_train.matmul(w) + b

  cost = torch.mean((hyperthesis - y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 1000 == 0:
    print(f"Epoch {epoch:4d}/{nb_epochs} hypothesis: {hyperthesis.squeeze().detach()} Cost: {cost.item():.6f}")

print(f"w: {w.squeeze().detach()}, b: {b.item()}")
print(x_train.matmul(w) + b)
print(y_train)

Epoch    0/10000 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch 1000/10000 hypothesis: tensor([152.4312, 183.9319, 180.8577, 196.9723, 140.4543]) Cost: 1.079390
Epoch 2000/10000 hypothesis: tensor([152.1425, 184.1316, 180.7716, 196.8914, 140.7322]) Cost: 0.754379
Epoch 3000/10000 hypothesis: tensor([151.9242, 184.2831, 180.7070, 196.8267, 140.9463]) Cost: 0.562653
Epoch 4000/10000 hypothesis: tensor([151.7595, 184.3978, 180.6588, 196.7742, 141.1117]) Cost: 0.448561
Epoch 5000/10000 hypothesis: tensor([151.6356, 184.4845, 180.6230, 196.7311, 141.2401]) Cost: 0.379734
Epoch 6000/10000 hypothesis: tensor([151.5428, 184.5499, 180.5967, 196.6953, 141.3400]) Cost: 0.337358
Epoch 7000/10000 hypothesis: tensor([151.4737, 184.5989, 180.5777, 196.6651, 141.4182]) Cost: 0.310486
Epoch 8000/10000 hypothesis: tensor([151.4225, 184.6355, 180.5640, 196.6393, 141.4799]) Cost: 0.292713
Epoch 9000/10000 hypothesis: tensor([151.3851, 184.6628, 180.5545, 196.6168, 141.5288]) Cost: 0.280

In [83]:
"""Linear Regresion with Module"""
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(1)

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

input_dim = 1
output_dim = 1

model = nn.Linear(input_dim, output_dim)
print(list(model.parameters()))

optimizer = optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print(f"Epoch {epoch:4d}/{nb_epochs} Cost: {cost.item():.6f}")

print(list(model.parameters()))
pred_y = model(x_train)
print(pred_y)
print(y_train)

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000
[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]
tensor([[2.0008],
        [4.0002],
        [5.9995]], grad_fn=<AddmmBackward0>)
tensor([[2.],
      

In [85]:
"""Multivariable Linear Regresion with Module"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

model = nn.Linear(3, 1)

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print(f"Epoch {epoch:4d}/{nb_epochs} Cost: {cost.item():.6f}")

print(list(model.parameters()))
pred_y = model(x_train)
print(pred_y)
print(y_train)

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769
[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]
tensor([[151.2305],
        [184.8005],
        [180.5203],
        [196.3101],
        [141.9926]], grad_fn=<AddmmBackward0>)
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]]

In [87]:
"""Liner Regresion with Class"""
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class LinearRegresionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1, 1)

  def forward(self, x):
    return self.linear(x)

torch.manual_seed(1)

model = LinearRegresionModel()
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
optimizer = optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  if epoch % 100 == 0:
    print(f"Epoch {epoch:4d}/{nb_epochs} Cost: {cost.item():.6f}")

print(list(model.parameters()))
pred_y = model(x_train)
print(pred_y)
print(y_train)

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000
[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]
tensor([[2.0008],
        [4.0002],
        [5.9995]], grad_fn=<AddmmBackward0>)
tensor([[2.],
        [4.],
        [6.]])


In [90]:
"""Multivariable Linear Segression with Class"""
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

class MultivariableLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3, 1)

  def forward(self, x):
    return self.linear(x)

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

model = MultivariableLinearRegressionModel()

optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  if epoch % 100 == 0:
    print(f"Epoch {epoch:4d}/{nb_epochs} Cost: {cost.item():.6f}")

print(list(model.parameters()))
pred_y = model(x_train)
print(pred_y)
print(y_train)

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769
[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]
tensor([[151.2305],
        [184.8005],
        [180.5203],
        [196.3101],
        [141.9926]], grad_fn=<AddmmBackward0>)
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]]